# Generated by Django 3.2.12 on 2024-07-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runserver', '0004_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
